package devflow_test

import (
	"fmt"
	"strings"
	"testing"
)

// fakeSumDB is an in-memory SumDBClient — no network, consistent with
// every other test in this package (local git repos, no real remotes
// beyond file:// bare repos). Keys are "modulePath@version".
type fakeSumDB struct {
	burned map[string]bool
	calls  []string
}

func (f *fakeSumDB) Lookup(modulePath, version string) (bool, error) {
	f.calls = append(f.calls, modulePath+"@"+version)
	return f.burned[modulePath+"@"+version], nil
}

// TestPush_ExplicitTagBurnedInSumDB_Fails is the regression this whole file
// exists for: veltylabs/iam's CI failed with
//
//	SECURITY ERROR: checksum mismatch
//	downloaded: h1:yFJTFgXK...
//	go.sum:     h1:HKO7gzbC...
//
// for webtyp.com/rbac@v0.0.4 — a version that had, at some point,
// been consulted through the public Go checksum database (sum.golang.org)
// with different content than what the tag currently holds. That database
// never updates an entry once recorded: reusing v0.0.4 was unrecoverable
// for any consumer building outside GOPRIVATE. gopush must refuse to tag
// an EXPLICIT version already burned there — silently substituting a
// different version would violate what the caller asked for.
func TestPush_ExplicitTagBurnedInSumDB_Fails(t *testing.T) {
	dir, cleanup := testCreateGoModule("github.com/test/repo")
	defer cleanup()
	defer testChdir(t, dir)()

	mockGit := &MockGitClient{}
	goHandler := newGoHandlerWithMockBackup(t, mockGit)

	sumdb := &fakeSumDB{burned: map[string]bool{"github.com/test/repo@v0.0.4": true}}
	goHandler.SetSumDBClient(sumdb)

	_, err := goHandler.Push("fix: something", "v0.0.4", true, true, true, true, false, true, "")
	if err == nil {
		t.Fatal("expected Push to refuse an explicit tag already burned in the public checksum database")
	}
	if !strings.Contains(err.Error(), "v0.0.4") {
		t.Errorf("error should name the burned tag, got: %v", err)
	}
	if mockGit.LastPushTag == "v0.0.4" {
		t.Error("git.Push must never be called with the burned tag")
	}
}

// TestPush_AutoGeneratedTagBurnedInSumDB_Increments proves the auto-bump
// path (tag == "") is free to keep incrementing past a burned version —
// unlike an explicit tag, no caller intent is being overridden by moving
// from v0.0.4 to v0.0.5.
func TestPush_AutoGeneratedTagBurnedInSumDB_Increments(t *testing.T) {
	dir, cleanup := testCreateGoModule("github.com/test/repo")
	defer cleanup()
	defer testChdir(t, dir)()

	mockGit := &MockGitClient{nextTagOverride: "v0.0.4"}
	goHandler := newGoHandlerWithMockBackup(t, mockGit)

	sumdb := &fakeSumDB{burned: map[string]bool{"github.com/test/repo@v0.0.4": true}}
	goHandler.SetSumDBClient(sumdb)

	result, err := goHandler.Push("fix: something", "", true, true, true, true, false, true, "")
	if err != nil {
		t.Fatalf("Push: %v", err)
	}
	if result.Tag != "v0.0.5" {
		t.Errorf("tag: got %q, want %q (v0.0.4 was burned, must skip to the next free version)", result.Tag, "v0.0.5")
	}
	if mockGit.LastPushTag != "v0.0.5" {
		t.Errorf("git.Push was called with %q, want %q", mockGit.LastPushTag, "v0.0.5")
	}
}

// TestPush_SumDBClientNilPreservesCurrentBehavior proves the check is
// fully additive: a caller that never calls SetSumDBClient (nil, the
// default) gets byte-for-byte the same behavior as before this option
// existed — same tag, no extra lookups, no new failure mode.
func TestPush_SumDBClientNilPreservesCurrentBehavior(t *testing.T) {
	dir, cleanup := testCreateGoModule("github.com/test/repo")
	defer cleanup()
	defer testChdir(t, dir)()

	mockGit := &MockGitClient{}
	goHandler := newGoHandlerWithMockBackup(t, mockGit)
	// No SetSumDBClient call.

	result, err := goHandler.Push("fix: something", "v0.0.4", true, true, true, true, false, true, "")
	if err != nil {
		t.Fatalf("Push: %v", err)
	}
	if result.Tag != "v0.0.4" {
		t.Errorf("tag: got %q, want %q (no SumDBClient configured — nothing should change)", result.Tag, "v0.0.4")
	}
}

type errorSumDB struct {
	err error
}

func (e *errorSumDB) Lookup(modulePath, version string) (bool, error) {
	return false, e.err
}

// TestPush_SumDBLookupError_FailsOpen proves that when sumdb lookup fails
// (e.g., network down), Push fails open (logs the error and proceeds with the requested tag).
func TestPush_SumDBLookupError_FailsOpen(t *testing.T) {
	dir, cleanup := testCreateGoModule("github.com/test/repo")
	defer cleanup()
	defer testChdir(t, dir)()

	mockGit := &MockGitClient{}
	goHandler := newGoHandlerWithMockBackup(t, mockGit)

	var logged []string
	goHandler.SetLog(func(args ...any) {
		var parts []string
		for _, a := range args {
			parts = append(parts, strings.TrimSpace(fmt.Sprint(a)))
		}
		logged = append(logged, strings.Join(parts, " "))
	})

	sumdb := &errorSumDB{err: fmt.Errorf("network connection refused")}
	goHandler.SetSumDBClient(sumdb)

	result, err := goHandler.Push("fix: something", "v0.0.4", true, true, true, true, false, true, "")
	if err != nil {
		t.Fatalf("Push failed when sumdb lookup returned an error: %v", err)
	}
	if result.Tag != "v0.0.4" {
		t.Errorf("tag: got %q, want %q (should fail open on sumdb lookup error)", result.Tag, "v0.0.4")
	}

	foundLog := false
	for _, l := range logged {
		if strings.Contains(l, "sumdb check skipped:") && strings.Contains(l, "network connection refused") {
			foundLog = true
			break
		}
	}
	if !foundLog {
		t.Errorf("expected log to contain sumdb skip warning, got: %v", logged)
	}
}
