package devflow_test

import "webtyp.com/devflow"

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGetBadgeColor(t *testing.T) {
	tests := []struct {
		typ   string
		value string
		want  string
	}{
		{"license", "MIT", "#007acc"},
		{"go", "1.20", "#007acc"},
		{"tests", "Passing", "#4c1"},
		{"tests", "Failed", "#e05d44"},
		{"coverage", "85", "#4c1"},
		{"coverage", "65", "#dfb317"},
		{"coverage", "30", "#fe7d37"},
		{"coverage", "0", "#e05d44"},
		{"race", "Clean", "#4c1"},
		{"race", "Detected", "#e05d44"},
		{"vet", "OK", "#4c1"},
		{"vet", "Issues", "#e05d44"},
	}

	for _, tt := range tests {
		got := devflow.GetBadgeColor(tt.typ, tt.value)
		if got != tt.want {
			t.Errorf("devflow.GetBadgeColor(%q, %q) = %q, want %q", tt.typ, tt.value, got, tt.want)
		}
	}
}

func TestGetGoVersion(t *testing.T) {
	version := devflow.GetGoVersion()
	if version == "" {
		t.Error("Expected non-empty go version")
	}
}

func TestBadgeMarkdown_Default(t *testing.T) {
	// Provide an arg so NewBadges doesn't return nil
	h := devflow.NewBadges("output_svgfile:docs/img/custom.svg")
	if h == nil {
		t.Fatal("NewBadges returned nil")
	}
	if err := h.Err(); err != nil {
		t.Fatalf("NewBadges returned error: %v", err)
	}

	want := `<img src="docs/img/custom.svg">`
	got := h.BadgeMarkdown()
	if got != want {
		t.Fatalf("unexpected markdown:\n got: %s\nwant: %s", got, want)
	}
}

func TestBadgeMarkdown_DefaultHandlerValue(t *testing.T) {
	// When created with no special args the default outputFile should be used
	h := devflow.NewBadges("dummy")
	if h == nil {
		t.Fatal("NewBadges returned nil")
	}
	if err := h.Err(); err != nil {
		t.Fatalf("NewBadges returned error: %v", err)
	}

	want := `<img src="docs/img/badges.svg">`
	got := h.BadgeMarkdown()
	if got != want {
		t.Fatalf("unexpected markdown:\n got: %s\nwant: %s", got, want)
	}
}

func TestGenerate_MatchesExpected(t *testing.T) {
	// args designed to produce the expected.svg in testdata
	args := []string{
		"License:MIT:#007acc",
		"Go:1.24.4:#00ADD8",
		"Tests:Passing:#4c1",
		"Coverage:73%:#dfb317",
		"Race:Clean:#4c1",
		"Vet:OK:#4c1",
	}

	h := devflow.NewBadges(args...)
	if h == nil {
		t.Fatalf("NewBadges returned nil")
	}
	if err := h.Err(); err != nil {
		t.Fatalf("NewBadges error: %v", err)
	}

	svgBytes, _, err := h.GenerateSVG()
	if err != nil {
		t.Fatalf("GenerateSVG error: %v", err)
	}
	svg := string(svgBytes)

	wantPath := filepath.Join("testdata", "expected.svg")
	wantBytes, rerr := os.ReadFile(wantPath)
	if rerr != nil {
		t.Fatalf("read expected file: %v", rerr)
	}

	got := strings.TrimSpace(svg)
	want := strings.TrimSpace(string(wantBytes))

	if got != want {
		t.Fatalf("generated SVG differs from expected\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestBuildBadges_UpdatesReadme verifies that BuildBadges updates the README with the new badge format
func TestBuildBadges_UpdatesReadme(t *testing.T) {
	tmp := t.TempDir()
	svgOut := filepath.Join(tmp, "badges.svg")
	readmeFile := filepath.Join(tmp, "README.md")

	// Create a README with some initial content
	initialContent := "# My Project\n\nSome text here.\n"
	if err := os.WriteFile(readmeFile, []byte(initialContent), 0o644); err != nil {
		t.Fatalf("setup: write readme: %v", err)
	}

	// Create handler with explicit output and readme file settings
	h := devflow.NewBadges("output_svgfile:"+svgOut, "readmefile:"+readmeFile, "License:MIT:#007acc")
	if h == nil {
		t.Fatal("NewBadges returned nil")
	}
	if err := h.Err(); err != nil {
		t.Fatalf("handler init error: %v", err)
	}

	if _, err := h.BuildBadges(); err != nil {
		t.Fatalf("BuildBadges error: %v", err)
	}

	// Verify README was updated with badge line
	readmeContent, err := os.ReadFile(readmeFile)
	if err != nil {
		t.Fatalf("read updated readme: %v", err)
	}
	readmeStr := string(readmeContent)

	// Should contain the badge img line
	if !strings.Contains(readmeStr, `<img src=`) {
		t.Errorf("README missing badge img line. Content:\n%s", readmeStr)
	}

	// Should NOT contain old section markers
	if strings.Contains(readmeStr, "START_SECTION") || strings.Contains(readmeStr, "END_SECTION") {
		t.Errorf("README contains old section markers. Content:\n%s", readmeStr)
	}

	// Verify SVG file was written
	info, err := os.Stat(svgOut)
	if err != nil {
		t.Fatalf("expected output file %s to exist: %v", svgOut, err)
	}
	if info.Size() == 0 {
		t.Fatalf("output file %s is empty", svgOut)
	}
}

// TestBuildBadges_MigrateOldMarkers verifies old START/END markers are removed
func TestBuildBadges_MigrateOldMarkers(t *testing.T) {
	tmp := t.TempDir()
	svgOut := filepath.Join(tmp, "badges.svg")
	readmeFile := filepath.Join(tmp, "README.md")

	// Create a README with old badge markers
	oldContent := `# My Project
<!-- START_SECTION:BADGES_SECTION -->
<a href="docs/img/badges.svg"><img src="docs/img/badges.svg" alt="Project Badges" title="Generated by devflow from webtyp.com/devflow"></a>
<!-- END_SECTION:BADGES_SECTION -->

Some text here.
`
	if err := os.WriteFile(readmeFile, []byte(oldContent), 0o644); err != nil {
		t.Fatalf("setup: write readme: %v", err)
	}

	h := devflow.NewBadges("output_svgfile:"+svgOut, "readmefile:"+readmeFile, "License:MIT:#007acc")
	if h == nil {
		t.Fatal("NewBadges returned nil")
	}

	_, err := h.BuildBadges()
	if err != nil {
		t.Fatalf("BuildBadges error: %v", err)
	}

	readmeContent, err := os.ReadFile(readmeFile)
	if err != nil {
		t.Fatalf("read updated readme: %v", err)
	}
	readmeStr := string(readmeContent)

	// Should contain new badge format only
	if !strings.Contains(readmeStr, `<img src="`) {
		t.Errorf("README missing new badge img line")
	}

	// Old markers should be gone
	if strings.Contains(readmeStr, "START_SECTION") || strings.Contains(readmeStr, "END_SECTION") {
		t.Errorf("README still contains old section markers")
	}

	// Old verbose format should be gone
	if strings.Contains(readmeStr, `alt="Project Badges"`) {
		t.Errorf("README contains old badge format attributes")
	}
}

// TestBuildBadges_ReplaceExistingImg verifies existing img lines are updated
func TestBuildBadges_ReplaceExistingImg(t *testing.T) {
	tmp := t.TempDir()
	svgOut := filepath.Join(tmp, "new_badges.svg")
	readmeFile := filepath.Join(tmp, "README.md")

	// Create a README with existing badge img line
	existingContent := `# My Project
<img src="docs/img/old_badges.svg">

Some text here.
`
	if err := os.WriteFile(readmeFile, []byte(existingContent), 0o644); err != nil {
		t.Fatalf("setup: write readme: %v", err)
	}

	h := devflow.NewBadges("output_svgfile:"+svgOut, "readmefile:"+readmeFile, "License:MIT:#007acc")
	if h == nil {
		t.Fatal("NewBadges returned nil")
	}

	_, err := h.BuildBadges()
	if err != nil {
		t.Fatalf("BuildBadges error: %v", err)
	}

	readmeContent, err := os.ReadFile(readmeFile)
	if err != nil {
		t.Fatalf("read updated readme: %v", err)
	}
	readmeStr := string(readmeContent)

	// Should contain new path
	if !strings.Contains(readmeStr, `<img src="`+svgOut+`">`) {
		t.Errorf("README not updated with new badge path. Content:\n%s", readmeStr)
	}

	// Old path should be gone
	if strings.Contains(readmeStr, "old_badges.svg") {
		t.Errorf("README still contains old badge path")
	}
}

// TestUpdateBadges_ViaGotest simulates the full gotest flow calling UpdateBadges on a README
// with the old verbose format. This is the exact scenario that caused 4 lines in the README.
func TestUpdateBadges_ViaGotest(t *testing.T) {
	tmp := t.TempDir()
	readmeFile := filepath.Join(tmp, "README.md")

	// This is the exact old format found in repos like webtyp/mcp
	oldFormat := `# My Module
<!-- START_SECTION:BADGES_SECTION -->
<a href="docs/img/badges.svg"><img src="docs/img/badges.svg" alt="Project Badges" title="Generated by devflow from webtyp.com/devflow"></a>
<!-- END_SECTION:BADGES_SECTION -->

Some description here.
`
	if err := os.WriteFile(readmeFile, []byte(oldFormat), 0o644); err != nil {
		t.Fatalf("setup: %v", err)
	}

	// Simulate what gotest does: creates NewBadges() with no args and calls updateBadges
	bh := devflow.NewBadges("dummy") // needs at least one arg to not error on init
	if bh.Err() != nil {
		t.Fatalf("NewBadges error: %v", bh.Err())
	}

	err := bh.UpdateBadges(readmeFile, "MIT", "1.24", "Passing", "90", "Clean", "OK", true)
	if err != nil {
		t.Fatalf("UpdateBadges error: %v", err)
	}

	content, err := os.ReadFile(readmeFile)
	if err != nil {
		t.Fatalf("read readme: %v", err)
	}
	got := string(content)

	// Exactly ONE img line
	count := strings.Count(got, `<img src="`)
	if count != 1 {
		t.Errorf("expected 1 badge img line, got %d\nContent:\n%s", count, got)
	}

	// No old markers
	if strings.Contains(got, "START_SECTION") || strings.Contains(got, "END_SECTION") {
		t.Errorf("old markers still present\nContent:\n%s", got)
	}

	// No <a> wrapper
	if strings.Contains(got, "<a href=") {
		t.Errorf("<a> wrapper still present\nContent:\n%s", got)
	}

	// Second call (idempotent)
	bh2 := devflow.NewBadges("dummy")
	if err := bh2.UpdateBadges(readmeFile, "MIT", "1.24", "Passing", "90", "Clean", "OK", true); err != nil {
		t.Fatalf("second UpdateBadges error: %v", err)
	}

	content2, _ := os.ReadFile(readmeFile)
	if strings.Count(string(content2), `<img src="`) != 1 {
		t.Errorf("after second call: duplicate badge lines\nContent:\n%s", string(content2))
	}
}

// TestBuildBadges_NoDoubleInsertion verifies old format with <a> tags doesn't cause duplication
// This tests the exact issue found in webtyp/mcp README where running badges twice
// on the old format results in duplicate img lines
func TestBuildBadges_NoDoubleInsertion(t *testing.T) {
	tmp := t.TempDir()
	svgOut := filepath.Join(tmp, "badges.svg")
	readmeFile := filepath.Join(tmp, "README.md")

	// Create a README with OLD verbose format (with <a> wrapper)
	oldFormat := `# My Project
<!-- START_SECTION:BADGES_SECTION -->
<a href="docs/img/badges.svg"><img src="docs/img/badges.svg" alt="Project Badges" title="Generated by devflow from webtyp.com/devflow"></a>
<!-- END_SECTION:BADGES_SECTION -->

Some description here.
`
	if err := os.WriteFile(readmeFile, []byte(oldFormat), 0o644); err != nil {
		t.Fatalf("setup: write readme: %v", err)
	}

	// First run: migrate old format
	h1 := devflow.NewBadges("output_svgfile:"+svgOut, "readmefile:"+readmeFile, "License:MIT:#007acc")
	if h1 == nil {
		t.Fatal("NewBadges returned nil")
	}

	_, err := h1.BuildBadges()
	if err != nil {
		t.Fatalf("first BuildBadges error: %v", err)
	}

	content1, err := os.ReadFile(readmeFile)
	if err != nil {
		t.Fatalf("read after first run: %v", err)
	}
	contentStr1 := string(content1)

	// Verify first run result: should have exactly ONE badge line
	badgeLineCount := strings.Count(contentStr1, `<img src="`)
	if badgeLineCount != 1 {
		t.Errorf("After first run: expected 1 badge img line, got %d\nContent:\n%s", badgeLineCount, contentStr1)
	}

	// Verify no old markers remain
	if strings.Contains(contentStr1, "START_SECTION") || strings.Contains(contentStr1, "END_SECTION") {
		t.Errorf("After first run: old markers still present\nContent:\n%s", contentStr1)
	}

	// Verify no <a> tag wrapper
	if strings.Contains(contentStr1, "<a href=") {
		t.Errorf("After first run: old <a> wrapper still present\nContent:\n%s", contentStr1)
	}

	// Second run: update should be idempotent
	h2 := devflow.NewBadges("output_svgfile:"+svgOut, "readmefile:"+readmeFile, "License:MIT:#007acc")
	if h2 == nil {
		t.Fatal("NewBadges returned nil")
	}

	_, err = h2.BuildBadges()
	if err != nil {
		t.Fatalf("second BuildBadges error: %v", err)
	}

	content2, err := os.ReadFile(readmeFile)
	if err != nil {
		t.Fatalf("read after second run: %v", err)
	}
	contentStr2 := string(content2)

	// Verify second run didn't duplicate: still exactly ONE badge line
	badgeLineCount2 := strings.Count(contentStr2, `<img src="`)
	if badgeLineCount2 != 1 {
		t.Errorf("After second run: expected 1 badge img line, got %d\nContent:\n%s", badgeLineCount2, contentStr2)
	}

	// Content should be identical after second run (idempotent)
	if contentStr1 != contentStr2 {
		t.Errorf("Second run changed content (not idempotent)\nFirst:\n%s\n\nSecond:\n%s", contentStr1, contentStr2)
	}
}
